# Generated by Django 5.0.1 on 2024-01-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
