# Generated by Django 5.0.1 on 2024-02-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_hemis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
